// <auto-generated />
namespace TempoDigitalApex3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class YT_ART_TRACK_Report_2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YT_ART_TRACK_Report_2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202010201554449_YT_ART_TRACK_Report_2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
