// <auto-generated />
namespace TempoDigitalApex3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_AS_Source : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_AS_Source));
        
        string IMigrationMetadata.Id
        {
            get { return "202106142125312_Update_AS_Source"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
